/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.RedefinirSenhas;
import Model.Logins;
/**
 *
 * @author User
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public MenuPrincipal() {
        initComponents();
         sobre_menu.setEnabled(false);
         fornecedores_menu.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fornecedores_menu = new javax.swing.JButton();
        usuarios_menu = new javax.swing.JButton();
        produtos_menu = new javax.swing.JButton();
        sobre_menu = new javax.swing.JButton();
        vendas_menu = new javax.swing.JButton();
        relatorios_menu = new javax.swing.JButton();
        sair_menu = new javax.swing.JButton();
        nome_menu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Area Principal");
        getContentPane().setLayout(null);

        fornecedores_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fornecedores_menu.setText("Fornecedores");
        getContentPane().add(fornecedores_menu);
        fornecedores_menu.setBounds(60, 260, 193, 65);

        usuarios_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuarios_menu.setText("Usuários");
        usuarios_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarios_menuActionPerformed(evt);
            }
        });
        getContentPane().add(usuarios_menu);
        usuarios_menu.setBounds(60, 340, 193, 61);

        produtos_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        produtos_menu.setText("Produtos");
        produtos_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtos_menuActionPerformed(evt);
            }
        });
        getContentPane().add(produtos_menu);
        produtos_menu.setBounds(300, 260, 193, 65);

        sobre_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sobre_menu.setText("Sobre");
        sobre_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobre_menuActionPerformed(evt);
            }
        });
        getContentPane().add(sobre_menu);
        sobre_menu.setBounds(300, 340, 193, 61);

        vendas_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vendas_menu.setText("Vendas");
        vendas_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendas_menuActionPerformed(evt);
            }
        });
        getContentPane().add(vendas_menu);
        vendas_menu.setBounds(540, 260, 191, 65);

        relatorios_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        relatorios_menu.setText("Relatórios");
        relatorios_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorios_menuActionPerformed(evt);
            }
        });
        getContentPane().add(relatorios_menu);
        relatorios_menu.setBounds(540, 340, 191, 61);

        sair_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sair_menu.setText("Fazer Logout");
        sair_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_menuActionPerformed(evt);
            }
        });
        getContentPane().add(sair_menu);
        sair_menu.setBounds(910, 440, 185, 50);

        nome_menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(nome_menu);
        nome_menu.setBounds(120, 10, 130, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Bem vindo,");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 10, 90, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View_imagens/area principal.png"))); // NOI18N
        jLabel2.setText("hviodh");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1192, 556);

        jMenu1.setText("Opções");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1167, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarios_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarios_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        Usuarios usuarios = new Usuarios();
        usuarios.setVisible(true);
    }//GEN-LAST:event_usuarios_menuActionPerformed

    private void sair_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_sair_menuActionPerformed

    private void produtos_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtos_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        Produtos produtos = new Produtos();
        produtos.setVisible(true);
    }//GEN-LAST:event_produtos_menuActionPerformed

    private void vendas_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendas_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        Vendas vendas = new Vendas();   
        vendas.setVisible(true);
    }//GEN-LAST:event_vendas_menuActionPerformed

    private void relatorios_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorios_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        Relatorios relatorios = new Relatorios();
        relatorios.setVisible(true);
    }//GEN-LAST:event_relatorios_menuActionPerformed

    private void sobre_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobre_menuActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_sobre_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fornecedores_menu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JLabel nome_menu;
    private javax.swing.JButton produtos_menu;
    private javax.swing.JButton relatorios_menu;
    private javax.swing.JButton sair_menu;
    private javax.swing.JButton sobre_menu;
    private javax.swing.JButton usuarios_menu;
    private javax.swing.JButton vendas_menu;
    // End of variables declaration//GEN-END:variables

    
}
