
package View;
import Model.Conexao;
import Model.Usuario;
import Model_DAO.Usuarios_DAO;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Usuarios extends javax.swing.JFrame {

    Connection conexao2 = Conexao.getConexao();
    
    public Usuarios() {
        initComponents();
        
        nome.setEnabled(false);
        nome_de_usuario.setEnabled(false);
        senha.setEnabled(false);
        cadastrar_usuario.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigo_de_usuario = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        nome_de_usuario = new javax.swing.JTextField();
        senha = new javax.swing.JTextField();
        cadastrar_usuario = new javax.swing.JButton();
        excluir_usuario = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        consultar_usuario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CADASTRADO DE USUÁRIOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 40, 306, 23);

        jLabel2.setText("Codigo do usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 120, 101, 16);

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 170, 36, 16);

        codigo_de_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_de_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(codigo_de_usuario);
        codigo_de_usuario.setBounds(210, 120, 336, 22);
        getContentPane().add(nome);
        nome.setBounds(210, 170, 336, 22);
        getContentPane().add(nome_de_usuario);
        nome_de_usuario.setBounds(210, 230, 336, 22);
        getContentPane().add(senha);
        senha.setBounds(210, 280, 336, 22);

        cadastrar_usuario.setText("CADASTRAR");
        cadastrar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar_usuario);
        cadastrar_usuario.setBounds(160, 340, 96, 22);

        excluir_usuario.setText("EXCLUIR");
        excluir_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(excluir_usuario);
        excluir_usuario.setBounds(380, 340, 75, 22);

        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(480, 340, 73, 22);

        consultar_usuario.setText("CONSULTAR");
        consultar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(consultar_usuario);
        consultar_usuario.setBounds(270, 340, 97, 22);

        jLabel6.setText("Nome de Usuario:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 230, 95, 16);

        jLabel7.setText("Senha:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 280, 35, 16);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View_imagens/usuarios.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 680, 387);

        setSize(new java.awt.Dimension(695, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codigo_de_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_de_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_de_usuarioActionPerformed

    private void cadastrar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_usuarioActionPerformed
        // TODO add your handling code here:
        
        
        
        int codigo_de_usuario = Integer.parseInt(this.codigo_de_usuario.getText());
        String nome = this.nome.getText();
        String nome_de_usuario = this.nome_de_usuario.getText();
        String senha = this.senha.getText();
        
        Usuario u = new Usuario(codigo_de_usuario,nome,nome_de_usuario,senha);
        Usuarios_DAO ubanco = new Usuarios_DAO(conexao2);
        ubanco.cadastrar(u);
        
        this.codigo_de_usuario.setText("");
        this.nome.setText("");
        this.nome_de_usuario.setText("");
        this.senha.setText("");
        
        this.nome.setEnabled(false);
        this.nome_de_usuario.setEnabled(false);
        this.senha.setEnabled(false);
        cadastrar_usuario.setEnabled(false);
        consultar_usuario.setEnabled(true);
        excluir_usuario.setEnabled(true);
    }//GEN-LAST:event_cadastrar_usuarioActionPerformed

    private void consultar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_usuarioActionPerformed
        // TODO add your handling code here:
        
        
        int codigo_de_usuario = Integer.parseInt(this.codigo_de_usuario.getText());
        
        
        Usuarios_DAO p = new Usuarios_DAO(conexao2);
        Usuario usuario = p.Consultar(codigo_de_usuario);
        
        if(usuario != null){
            this.nome.setText(usuario.getNome());
            this.nome_de_usuario.setText(usuario.getNome_de_usuario());
            this.senha.setText(usuario.getSenha());
        }else{
            int op = JOptionPane.showConfirmDialog(this, "O código do usuario não existe!\ntente casdatrar um novo usuario!","casdatrar um novo usuario?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(op == 0){
        nome.setEnabled(true);
        nome_de_usuario.setEnabled(true);
        senha.setEnabled(true);
        cadastrar_usuario.setEnabled(true);
        excluir_usuario.setEnabled(false);
        consultar_usuario.setEnabled(false);
         this.codigo_de_usuario.setText("");
         this.nome.setText("");
         this.nome_de_usuario.setText("");
         this.senha.setText("");
            }
         this.codigo_de_usuario.setText("");

        }
    }//GEN-LAST:event_consultar_usuarioActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        dispose();
              
        new MenuPrincipal().setVisible(true);
                
        
    }//GEN-LAST:event_voltarActionPerformed

    private void excluir_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_usuarioActionPerformed
        // TODO add your handling code here:
        int codigo_de_usuario = Integer.parseInt(this.codigo_de_usuario.getText());
        
        Usuarios_DAO u = new Usuarios_DAO(conexao2);
        
        if (u.Consultar(codigo_de_usuario) != null) {
            u.excluir(codigo_de_usuario);
        }else{
            JOptionPane.showMessageDialog(null, "O campo de código está vazio.");
        }
        this.codigo_de_usuario.setText("");
    }//GEN-LAST:event_excluir_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_usuario;
    private javax.swing.JTextField codigo_de_usuario;
    private javax.swing.JButton consultar_usuario;
    private javax.swing.JButton excluir_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nome_de_usuario;
    private javax.swing.JTextField senha;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
